# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cp ./.env.example ./.env

      # check linting
      - run: yarn run lint

      # run tests!
      - run: yarn run testci

      - deploy:
                name: Staging Deploy
                command: |
                    if [ "${CIRCLE_BRANCH}" == "release/0.3.0" ]; then
                      echo "${HOST_KEY}" >> ~/.ssh/known_hosts

                      ssh ${HOST_NAME} << EOF
                        cd ${HOST_DIR}
                        git pull
                        npm install
                        docker-compose down
                        docker-compose up --build -d
EOF
                    fi


